public class MockAbstractionExtension implements IAbstractionExtension {
    private String branchName = "";

    public void setBranch(IBranch branch) {
        branchName = branch.getName();
    }

    public String generateCodeAbstraction() {
        if (branchName == "passCodeAbstractionGenerationBranch") {
            return "MockAutoGeneratedCodeAbstractionPass.txt";
        } else if(branchName == "failCodeAbstractionGenerationBranch") {
            return "MockAutoGeneratedCodeAbstractionFail.txt";
        } else {
            return null;
        }
    }
}
